apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: sukriti2001/mongo-microservice:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password
        - name: DB_HOST
          value: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
